# Merge

In [1]:
import pandas as pd

In [7]:
var1=pd.DataFrame({"A":[1,2,3,4], "B":[5,6,7,8]})
var2=pd.DataFrame({"A":[1,2,3,5], "C":[21,22,23,24]})
pd.merge(var1,var2)

   A  B   C
0  1  5  21
1  2  6  22
2  3  7  23

In [13]:
# how to merge: left, right, inner, outer
# pd.merge(var1,var2, how="left")
# pd.merge(var1,var2, how="right")
# pd.merge(var1,var2, how="inner")
pd.merge(var1,var2, how="outer")

   A    B     C
0  1  5.0  21.0
1  2  6.0  22.0
2  3  7.0  23.0
3  4  8.0   NaN
4  5  NaN  24.0

# Concat

In [15]:
var1=pd.Series([1,2,3,4])
var2=pd.Series([10,20,30,40])
pd.concat([var1,var2])

0     1
1     2
2     3
3     4
0    10
1    20
2    30
3    40
dtype: int64

In [17]:
var1=pd.DataFrame({"A":[1,2,3,4], "B":[5,6,7,8]})
var2=pd.DataFrame({"A":[1,2,3,5], "B":[21,22,23,24]})
pd.concat([var1,var2])

   A   B
0  1   5
1  2   6
2  3   7
3  4   8
0  1  21
1  2  22
2  3  23
3  5  24